apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- toYaml .Values.global.labels | nindent 4 }}
data:
  genesis.json: {{ tpl (.Files.Get "files/genesis.json") . | quote }}