apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-configmap
  namespace: {{ .Values.global.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.namespace }}
  name: create-configmap-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-configmap-rolebinding
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-configmap-role
subjects:
- kind: ServiceAccount
  name: create-configmap
  namespace: {{ .Values.global.namespace }}