{{- if not .Values.global.ethParameters.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: geth-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  NETWORK_ID: {{ .Values.global.ethParameters.NETWORK_ID | b64enc }}
  JWTSECRET: {{ .Values.global.ethParameters.JWTSECRET | b64enc }}
  ACCOUNT_ADDRESS: {{ .Values.global.ethParameters.ACCOUNT_ADDRESS | b64enc }}
  ACCOUNT_PASSWORD: |
    {{ if .Values.global.ethParameters.ACCOUNT_PASSWORD }}
    {{ .Values.global.ethParameters.ACCOUNT_PASSWORD | b64enc }}
    {{ else }}
    {{ "" }}
    {{ end }}
{{- end }}