{{- if not .Values.global.ethParameters.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: geth-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  ENODE: {{ .Values.global.ethParameters.ENODE | b64enc }}
  NODE_KEY_HEX: {{ .Values.global.ethParameters.NODE_KEY_HEX | b64enc }}
  NETWORK_ID: {{ .Values.global.ethParameters.NETWORK_ID | b64enc }}
  ACCOUNT_PASSWORD: {{ .Values.global.ethParameters.ACCOUNT_PASSWORD | b64enc }}
{{- end }}