apiVersion: v1
kind: Service
metadata:
  name: geth-rpc-endpoint
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- toYaml .Values.global.labels | nindent 4 }}
spec:
  type: {{ .Values.rpc.service.type }}
  ports:
    - port: {{ .Values.rpc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: geth-rpc-endpoint