apiVersion: v1
kind: Service
metadata:
  name: beacon-chain
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- toYaml .Values.global.labels | nindent 4 }}
spec:
  selector:
    app: beacon-chain
  ports:
    - name: port4000
      port: 4000
      targetPort: 4000
    - name: port3500
      port: 3500
      targetPort: 3500
    - name: port8080
      port: 8080
      targetPort: 8080
    - name: port6060
      port: 6060
      targetPort: 6060
    - name: port9090
      port: 9090
      targetPort: 9090